repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=100 ]
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: no-commit-to-branch
      - id: check-executables-have-shebangs
      - id: pretty-format-json
        args: [ "--autofix", "--no-sort-keys" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args:
          - --target-version=py311
          - --extend-select=I,UP,LOG
          - --fix
      - id: ruff-format
